name: voicevox_flutter
description: voicevox_core wrapper.
version: 0.1.3
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^7.2.9

flutter:
  plugin:
    platforms:
      android:
        package: com.example.voicevox_flutter
        pluginClass: VoicevoxFlutterPlugin
      ios:
        pluginClass: VoicevoxFlutterPlugin

ffigen:
  name: 'VoicevoxCoreLibrary'
  descrdescriptionipt: 'Bindings to voiceox_core_c_api'
  output: 'lib/generated_bindings.dart'
  llvm-path:
    - 'C:\Program Files\llvm'
  headers:
    entry-points:
      - 'voicevox_core.h'
    include-directives:
      - 'voicevox_core.h'
  compiler-opts:
    - '"-IC:\Program Files\LLVM\lib\clang\16\include\"'


scripts:
  # bindingクラスを生成する
  ffigen: flutter pub run ffigen